"""
Section 9 demo tenant, the remainder: 62 sections, 180 teachers (with logins),
timetable for the demo teacher, a second Class 6 section with 40 students, one
complete DARPAN term for two Class 6 sections (380 observations, full 360
inputs, 240 approved descriptors + 4 unapproved, 2 released reports), 180
SAARTHI artifacts (140 approved with visible edit distances, 3 in Hindi), CPD
for 40 teachers, exam calendar events. Writes supabase/seed/0013_demo.sql.
Everything is fictional and generated from name lists.
"""

import json
import random
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCHOOL = "a0000000-0000-0000-0000-000000000001"
TEACHER = "d0000000-0000-0000-0000-000000000001"
ACADEMIC = "d0000000-0000-0000-0000-000000000002"
HOD = "d0000000-0000-0000-0000-000000000003"
SECTION_6A = "c0000000-0000-0000-0000-000000000001"
SECTION_6B = "c0000000-0000-0000-0000-000000000006"
SUBJ = {"SCI": "b0000000-0000-0000-0000-000000000001", "MATH": "b0000000-0000-0000-0000-000000000002", "SST": "b0000000-0000-0000-0000-000000000004", "ENG": "b0000000-0000-0000-0000-000000000005"}
TERM = "T1 2026-27"
YEAR = "2026-27"
rng = random.Random(9)

FIRST = ["Aarav", "Diya", "Kabir", "Myra", "Vihaan", "Anika", "Reyansh", "Saanvi", "Arjun", "Ira", "Vivaan", "Kiara", "Ishaan", "Pari", "Ayaan", "Riya", "Advait", "Navya", "Rudra", "Tara", "Meher", "Zara", "Dev", "Yash", "Nikhil", "Ishita", "Tanvi", "Om", "Daksh", "Veer"]
LAST = ["Sharma", "Verma", "Iyer", "Nair", "Reddy", "Gupta", "Menon", "Rao", "Kulkarni", "Bose", "Chatterjee", "Mehta", "Joshi", "Kapoor", "Malhotra", "Bhatt", "Pillai", "Desai", "Chauhan", "Kaur"]
TFIRST = ["Asha", "Rohan", "Meera", "Suresh", "Anjali", "Ramesh", "Kavita", "Manoj", "Sunita", "Deepak", "Pooja", "Rajesh", "Neelam", "Vikram", "Shalini", "Arun", "Geeta", "Sanjay", "Rekha", "Amit"]


def uid(*p):
    return str(uuid.uuid5(uuid.NAMESPACE_URL, "acharya/demo/" + "/".join(p)))


def q(s):
    return "null" if s is None else "'" + str(s).replace("'", "''") + "'"


def jq(o):
    return q(json.dumps(o, ensure_ascii=False)) + "::jsonb"


def main():
    L = []
    w = L.append
    w("-- 0013_demo.sql -- GENERATED by worker/scripts/gen_demo_seed.py. Do not hand-edit. All fictional.")
    w("")
    # --- sections: Section 9 mapping. Existing: 6A(CBSE), 9A(CBSE), 9B(IGCSE), 10A(CBSE) -> add 58 more.
    plan = []
    for g in ["Nursery", "KG", "1", "2", "3", "4", "5"]:
        plan += [(g, "A", "CBSE"), (g, "B", "CBSE"), (g, "C", "CAMB_PRIMARY"), (g, "D", "CAMB_PRIMARY")]
    for g in ["6", "7", "8"]:
        plan += [(g, "B", "CBSE"), (g, "C", "CBSE"), (g, "D", "CAMB_LOWER_SEC"), (g, "E", "CAMB_LOWER_SEC")]
    plan += [("9", "C", "CBSE"), ("9", "D", "IGCSE"), ("9", "E", "IGCSE"), ("9", "F", "CBSE")]
    plan += [("10", "B", "CBSE"), ("10", "C", "CBSE"), ("10", "D", "IGCSE"), ("10", "E", "IGCSE")]
    for g in ["11", "12"]:
        plan += [(g, "A", "CBSE"), (g, "B", "CBSE"), (g, "C", "IB_DP"), (g, "D", "IB_DP"), (g, "E", "AP")]
    plan = plan[:58]
    w("insert into sections (id, school_id, grade, section, framework_id)")
    w("select v.id::uuid, " + q(SCHOOL) + ", v.grade, v.section, f.id from (values")
    rows = []
    for g, s, fw in plan:
        sid = SECTION_6B if (g, s) == ("6", "B") else uid("section", g, s)
        rows.append(f"  ({q(sid)}, {q(g)}, {q(s)}, {q(fw)})")
    w(",\n".join(rows) + ") as v(id, grade, section, fw) join frameworks f on f.code = v.fw;")
    w("")
    # --- 180 teachers with logins (177 new + 3 existing)
    w("create or replace function seed_auth_user(p_id uuid, p_email text, p_password text) returns uuid as $$")
    w("begin")
    w("  insert into auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at,")
    w("    confirmation_token, recovery_token, email_change_token_new, email_change, email_change_token_current, phone_change, phone_change_token, reauthentication_token)")
    w("  values ('00000000-0000-0000-0000-000000000000', p_id, 'authenticated', 'authenticated', p_email, crypt(p_password, gen_salt('bf', 4)), now(),")
    w("    '{\"provider\":\"email\",\"providers\":[\"email\"]}', '{}', now(), now(), '', '', '', '', '', '', '', '');")
    w("  insert into auth.identities (id, user_id, provider_id, identity_data, provider, created_at, updated_at)")
    w("  values (gen_random_uuid(), p_id, p_id::text, jsonb_build_object('sub', p_id::text, 'email', p_email), 'email', now(), now());")
    w("  return p_id;")
    w("end; $$ language plpgsql;")
    teachers = [TEACHER, ACADEMIC, HOD]
    tnames = {}
    for i in range(177):
        tid = uid("teacher", str(i))
        name = f"{TFIRST[i % 20]} {LAST[(i * 7) % 20]}"
        tnames[tid] = name
        teachers.append(tid)
        w(f"select seed_auth_user({q(tid)}, 'teacher{i + 4:03d}@kalanjali.demo', 'Demo@2026');")
    w("insert into profiles (id, school_id, full_name, role, subject_id) values")
    rows = []
    subj_keys = list(SUBJ)
    for i, tid in enumerate(teachers[3:]):
        role = "teacher"
        if i < 3:
            role = ["board_coordinator", "ct_ai_lead", "exam_officer"][i]
        rows.append(f"  ({q(tid)}, {q(SCHOOL)}, {q(tnames[tid])}, {q(role)}, {q(SUBJ[subj_keys[i % 4]])})")
    w(",\n".join(rows) + ";")
    w("update profiles set framework_id = (select id from frameworks where code = 'IB_DP') where role = 'board_coordinator' and school_id = " + q(SCHOOL) + ";")
    w("insert into profiles (id, school_id, full_name, role) select id, school_id, full_name, role from profiles where false;")
    # named demo logins from Section 9 for coordinators/leads (aliases)
    for i, (email, role_name) in enumerate([("ibcoord@kalanjali.demo", "board_coordinator"), ("ctlead@kalanjali.demo", "ct_ai_lead"), ("exam@kalanjali.demo", "exam_officer"), ("cambcoord@kalanjali.demo", "board_coordinator")]):
        tid = uid("named", email)
        w(f"select seed_auth_user({q(tid)}, {q(email)}, 'Demo@2026');")
        fw = "'IB_DP'" if email.startswith("ib") else "'IGCSE'" if email.startswith("camb") else "null"
        w(f"insert into profiles (id, school_id, full_name, role, framework_id) values ({q(tid)}, {q(SCHOOL)}, {q(['Priya Menon', 'Arun Pillai', 'Geeta Rao', 'Vikram Desai'][i])}, {q(role_name)}, (select id from frameworks where code = {fw}));")
    w("drop function seed_auth_user(uuid, text, text);")
    w("")
    # --- teaching assignments: 4 subjects per section, teachers round-robin
    w("insert into teaching_assignments (school_id, teacher_id, section_id, subject_id, academic_year)")
    w("select " + q(SCHOOL) + ", v.t::uuid, v.s::uuid, v.sub::uuid, " + q(YEAR) + " from (values")
    rows = []
    k = 0
    all_sections = [SECTION_6B if (g, s) == ("6", "B") else uid("section", g, s) for g, s, _ in plan]
    for sid in all_sections:
        for sk in subj_keys:
            rows.append(f"  ({q(teachers[3 + (k % 177)])}, {q(sid)}, {q(SUBJ[sk])})")
            k += 1
    # demo teacher also takes 6B Science (DARPAN across two class-6 sections)
    rows.append(f"  ({q(TEACHER)}, {q(SECTION_6B)}, {q(SUBJ['SCI'])})")
    w(",\n".join(rows) + ") as v(t, s, sub) on conflict do nothing;")
    w("")
    # --- 40 students in 6B with guardians + consents
    w("do $$ declare v_student uuid; v_guardian uuid; begin")
    w("for i in 1..40 loop")
    w("  v_student := gen_random_uuid(); v_guardian := gen_random_uuid();")
    w(f"  insert into students (id, school_id, admission_no, full_name, dob, section_id) values (v_student, {q(SCHOOL)}, 'KAL-2026-' || lpad((200 + i)::text, 4, '0'),")
    w("    (array['Aarav','Diya','Kabir','Myra','Vihaan','Anika','Reyansh','Saanvi','Arjun','Ira'])[1 + i % 10] || ' ' || (array['Sharma','Verma','Iyer','Nair','Reddy','Gupta','Menon','Rao'])[1 + i % 8],")
    w(f"    date '2014-05-01' + i * 6, {q(SECTION_6B)});")
    w(f"  insert into guardians (id, school_id, full_name, phone, email) values (v_guardian, {q(SCHOOL)}, 'Guardian ' || i, '98' || lpad((200000000 + i)::text, 8, '0'), 'guardian' || (200 + i) || '@example.test');")
    w("  insert into student_guardians (student_id, guardian_id, relation, is_primary) values (v_student, v_guardian, 'parent', true);")
    w(f"  insert into consent_records (school_id, student_id, guardian_id, purpose, consent_version, granted, via) select {q(SCHOOL)}, v_student, v_guardian, p, 'v1-2026', true, 'paper' from unnest(array['data_processing','parent_input','report_release','media_use']) p;")
    w("end loop; end $$;")
    w("")
    # --- DARPAN: one complete term for 6A + 6B (90 students): observations to reach 380, 360 inputs, descriptors
    obs_notes = [
        ("cognitive", "lab", "Predicted the outcome before the experiment and checked it against the result."),
        ("cognitive", "class discussion", "Asked a why-question that moved the whole discussion forward."),
        ("affective", "presentation", "Kept going after losing the thread; recovered without prompting."),
        ("socio_emotional", "group work", "Made sure the quietest member of the group got to present a point."),
        ("psychomotor", "sport", "Improved throwing accuracy across three sessions; still rushes the release."),
        ("psychomotor", "art", "Careful, controlled line work on the diagram; used the ruler without being asked."),
        ("affective", "homework", "Brought an extra example from home and explained it to the class."),
        ("socio_emotional", "play", "Resolved a disagreement over turns by proposing a rota."),
    ]
    w("-- observations: bring the two Class 6 sections to 380 in total (existing 48 for 6A students 1-8)")
    w("insert into observations (school_id, student_id, teacher_id, domain, context, note, observed_on)")
    w("select st.school_id, st.id, " + q(TEACHER) + ", o.domain, o.context, o.note, current_date - o.d")
    w("from (select id, school_id, row_number() over (order by admission_no) rn from students where section_id in (" + q(SECTION_6A) + ", " + q(SECTION_6B) + ")) st")
    w("cross join lateral (select * from (values")
    rows = []
    for i, (d, c, n) in enumerate(obs_notes[:5]):
        rows.append(f"  ({q(d)}, {q(c)}, {q(n)}, {5 + i * 9})")
    w(",\n".join(rows) + ") as v(domain, context, note, d)) o")
    w("where (st.rn > 8 and (o.d < 40 or st.rn > 80)) or (st.rn <= 8 and o.d > 30)")   # 82x4 + 10 + 16 = 354 (+ existing) >= 380
    w(";")
    w("")
    w("-- 360 inputs for every Class 6 student who lacks them")
    for src, resp in [("self", {"enjoy_most": "Science experiments and art", "proud_of": "Finishing my project on time", "want_to_improve": "Speaking up in class", "help_needed": "Reminders to check my work"}),
                      ("peer", {"good_at": "Explaining maths steps", "kind_when": "Lent me a pencil and notes", "could_try": "Listening before answering"}),
                      ("parent", {"at_home": "Draws and reads comics", "interests": "Cricket, cooking", "concerns": "Rushes homework", "support_wanted": "A short daily routine"}),
                      ("teacher", {"participation": "Regular", "homework": "On time", "collaboration": "Good", "note": "Responds well to a checklist"})]:
        sub_by = q(TEACHER) if src == "teacher" else "null"
        sbs = "(select p.id from students p where p.section_id = st.section_id and p.id <> st.id order by p.admission_no limit 1)" if src == "peer" else ("st.id" if src == "self" else "null")
        w(f"insert into hpc_inputs (school_id, student_id, term, source, submitted_by, submitted_by_student, responses)")
        w(f"select st.school_id, st.id, {q(TERM)}, {q(src)}, {sub_by}, {sbs}, {jq(resp)} from students st")
        w(f"where st.section_id in ({q(SECTION_6A)}, {q(SECTION_6B)}) and not exists (select 1 from hpc_inputs i where i.student_id = st.id and i.term = {q(TERM)} and i.source = {q(src)});")
    w("")
    w("-- descriptors: 60 students fully approved (240), 4 students with one unapproved draft each")
    domains_txt = {
        "cognitive": "Explains ideas using the right terms and checks predictions against results; next term, write the conclusion before discussing it.",
        "affective": "Shows persistence and curiosity, bringing examples from home; keep noticing what helps when a task feels hard.",
        "socio_emotional": "Includes quieter classmates and resolves disagreements fairly; next, take a turn as the group's timekeeper.",
        "psychomotor": "Controlled, careful work in practical and physical tasks; slow the release when throwing.",
    }
    w("with ranked as (select id, school_id, row_number() over (order by section_id, admission_no) rn from students where section_id in (" + q(SECTION_6A) + ", " + q(SECTION_6B) + "))")
    w("insert into hpc_descriptors (id, school_id, student_id, term, domain, generated_text, generated_json, final_text, status, drafted_by)")
    w("select uuid_generate_v5('6ba7b810-9dad-11d1-80b4-00c04fd430c8', 'acharya/demo/desc/' || r.id || '/' || d.domain), r.school_id, r.id, " + q(TERM) + ", d.domain, d.txt,")
    w("  jsonb_build_object('strengths', array[d.txt], 'growth_areas', array['Keep the momentum next term.'], 'next_step', 'Agree one weekly goal with the class teacher.'), d.txt, 'draft', " + q(TEACHER))
    w("from ranked r cross join (values " + ", ".join(f"({q(k)}, {q(v)})" for k, v in domains_txt.items()) + ") as d(domain, txt)")
    w("where r.rn between 5 and 64 or (r.rn between 65 and 68 and d.domain <> 'psychomotor') or (r.rn between 65 and 68 and d.domain = 'psychomotor')")
    w("on conflict (student_id, term, domain) do nothing;")
    w("with ranked as (select id, row_number() over (order by section_id, admission_no) rn from students where section_id in (" + q(SECTION_6A) + ", " + q(SECTION_6B) + "))")
    w("insert into approvals (school_id, artifact_type, artifact_id, generated_version, final_version, edit_distance, approved_by, approved_at)")
    w("select d.school_id, 'descriptor', d.id, to_jsonb(d.generated_text), to_jsonb(d.final_text), (random() * 30)::int, " + q(TEACHER) + ", now() - (random() * interval '20 days')")
    w("from hpc_descriptors d join ranked r on r.id = d.student_id")
    w("where d.status = 'draft' and (r.rn between 5 and 64 or (r.rn between 65 and 68 and d.domain <> 'psychomotor'))")
    w("on conflict (artifact_type, artifact_id) do nothing;")
    w("update hpc_descriptors d set status = 'approved', approved_by = " + q(TEACHER) + ", approved_at = now() - interval '3 days'")
    w("where d.status = 'draft' and exists (select 1 from approvals a where a.artifact_type = 'descriptor' and a.artifact_id = d.id);")
    w("")
    # --- SAARTHI: 180 artifacts (existing few + generated), 140 approved with edit distances, 3 Hindi
    kinds = ["lesson_plan", "worksheet", "rubric", "parent_message", "activity", "remediation_set", "revision_sheet"]
    bodies = {
        "lesson_plan": {"title": "Photosynthesis in context", "objectives": [{"text": "Explain the inputs and outputs of photosynthesis", "outcome_ref": "CBSE.SCI.6.1.1"}, {"text": "Design a fair test on light", "outcome_ref": "CBSE.SCI.6.1.2"}], "hook": "Two identical plants, one in a cupboard for a week.", "sequence": [{"step": "Hook and predictions", "minutes": 8, "teacher_does": "Shows plants", "students_do": "Predict"}, {"step": "Core explanation", "minutes": 12, "teacher_does": "Diagram", "students_do": "Annotate"}, {"step": "Fair test design", "minutes": 15, "teacher_does": "Circulates", "students_do": "Plan in pairs"}, {"step": "Exit check", "minutes": 5, "teacher_does": "Collects", "students_do": "Answer"}], "checks_for_understanding": ["Thumbs poll on inputs", "Exit ticket"], "differentiation": {"support": "Word bank", "core": "Diagram from memory", "extension": "Predict the cupboard plant's mass"}, "closure": "Revisit predictions", "homework": "Observe a plant at home for 3 days"},
        "worksheet": {"title": "Fractions practice", "levels": {"support": {"instructions": "Use the fraction wall.", "questions": [{"q": "1/2 + 1/4", "marks": 1}, {"q": "Shade 3/4", "marks": 1}, {"q": "Which is bigger, 1/3 or 1/4?", "marks": 1}]}, "core": {"instructions": "Show working.", "questions": [{"q": "2/3 + 1/6", "marks": 2}, {"q": "5/8 - 1/4", "marks": 2}, {"q": "Order 2/5, 1/2, 3/10", "marks": 2}]}, "extension": {"instructions": "Explain your reasoning.", "questions": [{"q": "A recipe uses 3/4 cup for 6 people. For 8?", "marks": 3}, {"q": "Prove 1/2 > 3/7", "marks": 3}, {"q": "Two fractions summing to 1 with different denominators", "marks": 3}]}}, "answer_key": [{"level": "support", "answers": ["3/4", "diagram", "1/3"]}]},
        "rubric": {"title": "Lab report rubric", "task": "Write up the germination experiment", "criteria": [{"name": "Aim and hypothesis", "outcome_ref": "CBSE.SCI.6.1.1", "bands": [{"level": "Beginning", "descriptor": "Aim stated", "marks": 1}, {"level": "Developing", "descriptor": "Aim and a testable hypothesis", "marks": 2}, {"level": "Proficient", "descriptor": "Hypothesis links to variables", "marks": 3}, {"level": "Exemplary", "descriptor": "Justified with prior knowledge", "marks": 4}]}, {"name": "Method", "bands": [{"level": "Beginning", "descriptor": "Steps listed", "marks": 1}, {"level": "Developing", "descriptor": "Steps in order", "marks": 2}, {"level": "Proficient", "descriptor": "Fair test controls named", "marks": 3}, {"level": "Exemplary", "descriptor": "Repeatable by a peer", "marks": 4}]}, {"name": "Conclusion", "bands": [{"level": "Beginning", "descriptor": "Result stated", "marks": 1}, {"level": "Developing", "descriptor": "Result explained", "marks": 2}, {"level": "Proficient", "descriptor": "Linked to hypothesis", "marks": 3}, {"level": "Exemplary", "descriptor": "Limitations discussed", "marks": 4}]}]},
        "parent_message": {"subject": "A good week in Science", "message": "Namaste. This week your child set up the germination tray carefully and explained to the group why the cotton had to stay moist. At home, you could ask them to describe what changed each day. I would be glad to talk at the next parent meeting."},
        "activity": {"title": "Human food chain", "duration_minutes": 30, "materials": ["Cards", "String"], "steps": ["Hand out organism cards", "Students link with string", "Remove one organism, discuss"], "assessment_note": "Look for correct arrow direction and reasoning about energy."},
        "remediation_set": {"weak_outcomes": [{"ref_code": "CBSE.SCI.10.1.1", "statement": "Recall cell structure", "avg": 0.42, "source": "bank", "items": [{"stem": "Label the parts of a plant cell.", "marks": 2}]}], "bank_first": True, "generated_for": [], "needs_generation": []},
        "revision_sheet": {"title": "Unit 1 revision", "sections": [{"outcome_ref": "CBSE.SCI.6.1.1", "key_points": ["Inputs: light, water, CO2", "Outputs: glucose, oxygen"], "common_errors": ["Confusing respiration with photosynthesis"], "practice": ["Name two inputs", "Why is chlorophyll needed?"]}]},
    }
    w("-- 180 SAARTHI artifacts (140 approved with edit distances; 3 Hindi)")
    w("do $$ declare v uuid; k text; i int; n_existing int; begin")
    w("select count(*) into n_existing from artifacts where school_id = " + q(SCHOOL) + ";")
    w("for i in 1..(180 - n_existing) loop")
    w("  k := (array['lesson_plan','worksheet','rubric','parent_message','activity','remediation_set','revision_sheet'])[1 + i % 7];")
    w("  v := create_artifact(jsonb_build_object('school_id', " + q(SCHOOL) + ", 'kind', k,")
    w("     'title', (case k " + " ".join(f"when {q(kk)} then {q(bodies[kk].get('title') or bodies[kk].get('subject') or 'Remediation set: Unit 1')}" for kk in kinds) + " end) || ' #' || i,")
    w("     'body', (case k " + " ".join(f"when {q(kk)} then {jq(bodies[kk])}" for kk in kinds) + " end),")
    w("     'generated_version', (case k " + " ".join(f"when {q(kk)} then {jq(bodies[kk])}" for kk in kinds) + " end),")
    w("     'subject_id', " + q(SUBJ["SCI"]) + ", 'grade', '6', 'framework_id', (select id from frameworks where code = 'CBSE'), 'section_id', " + q(SECTION_6A) + ",")
    w("     'language', case when i <= 3 then 'hi' else 'en' end, 'origin', 'ai_generated', 'created_by', (case when i % 3 = 0 then " + q(TEACHER) + " else " + q(HOD) + " end)),")
    w("     array[(select id from learning_outcomes where ref_code = 'CBSE.SCI.6.1.1' and school_id = " + q(SCHOOL) + ")]::uuid[]);")
    w("  if i <= 140 then")
    w("    insert into approvals (school_id, artifact_type, artifact_id, generated_version, final_version, edit_distance, approved_by, approved_at)")
    w("    select a.school_id, 'artifact', a.id, a.generated_version, a.body, (random() * 120)::int, " + q(TEACHER) + ", now() - (random() * interval '80 days') from artifacts a where a.id = v;")
    w("    update artifacts set status = 'approved', approved_by = " + q(TEACHER) + ", approved_at = now() - interval '1 day' where id = v;")
    w("    if i % 4 = 0 then insert into artifact_shares (artifact_id, shared_with_role, shared_with_subject, shared_by) values (v, 'teacher', " + q(SUBJ["SCI"]) + ", " + q(TEACHER) + "); update artifacts set status = 'shared' where id = v; end if;")
    w("  end if;")
    w("end loop; end $$;")
    w("update artifacts set title = replace(title, 'A good week in Science', 'विज्ञान में एक अच्छा सप्ताह'), body = jsonb_set(body, '{subject}', '\"विज्ञान में एक अच्छा सप्ताह\"') where language = 'hi' and kind = 'parent_message';")
    w("")
    # --- CPD for 40 teachers
    w("insert into cpd_records (school_id, teacher_id, activity, hours, completed_on)")
    w("select " + q(SCHOOL) + ", id, (array['District Level Deliberation','CBSE CoE workshop','in-house'])[1 + (row_number() over ()) % 3], (3 + (row_number() over ()) % 4)::int, date '2026-05-01' + ((row_number() over ()) * 3)::int")
    w("from (select id from profiles where school_id = " + q(SCHOOL) + " and role in ('teacher','hod','ct_ai_lead') and id not in (select teacher_id from cpd_records) order by full_name limit 37) t;")
    w("")
    # --- timetable for the demo teacher: Mon-Sat, 6 periods
    w("insert into timetable_periods (school_id, section_id, subject_id, teacher_id, weekday, period_no, starts_at, ends_at, academic_year) values")
    rows = []
    slots = [("08:00", "08:40"), ("08:45", "09:25"), ("09:30", "10:10"), ("10:30", "11:10"), ("11:15", "11:55"), ("12:00", "12:40")]
    secs = [SECTION_6A, "c0000000-0000-0000-0000-000000000003", "c0000000-0000-0000-0000-000000000004", "c0000000-0000-0000-0000-000000000005", SECTION_6B, SECTION_6A]
    for wd in range(1, 7):
        for pn, (a, b) in enumerate(slots, start=1):
            if (wd + pn) % 3 == 0:
                continue   # free periods
            rows.append(f"  ({q(SCHOOL)}, {q(secs[(wd + pn) % 6])}, {q(SUBJ['SCI'])}, {q(TEACHER)}, {wd}, {pn}, '{a}', '{b}', {q(YEAR)})")
    w(",\n".join(rows) + ";")
    w("")
    # --- exam calendar: Class 10 two-exam system
    w("insert into exam_events (school_id, title, kind, grade, framework_id, starts_on, ends_on, note) values")
    w(",\n".join([
        f"  ({q(SCHOOL)}, 'CBSE Class 10 Board — Main examination', 'board_main', '10', (select id from frameworks where code = 'CBSE'), date '2027-02-15', date '2027-03-10', 'First of the two board examinations')",
        f"  ({q(SCHOOL)}, 'CBSE Class 10 Board — Improvement examination (optional)', 'board_improvement', '10', (select id from frameworks where code = 'CBSE'), date '2027-05-05', date '2027-05-20', 'Best score counts')",
        f"  ({q(SCHOOL)}, 'Preboard correction window', 'correction_window', '10', (select id from frameworks where code = 'CBSE'), date '2027-01-20', date '2027-01-27', 'Two preboards, matched blueprints')",
        f"  ({q(SCHOOL)}, 'Main board result', 'result', '10', (select id from frameworks where code = 'CBSE'), date '2027-04-15', null, null)",
    ]) + ";")
    w("")
    # --- generation_log: one synthetic gateway record per seeded AI artifact/item/descriptor so the
    # leadership view reads like a real term. Hash only, never a prompt; redaction counts are synthetic.
    w("-- synthetic generation_log rows for seeded AI output (hash only; no prompt text is ever stored)")
    w("insert into generation_log (school_id, actor_id, template_key, template_version, provider, model, redacted_prompt_hash, redaction_count, input_tokens, output_tokens, latency_ms, validation_result, artifact_type, artifact_id, created_at)")
    w("select a.school_id, coalesce(a.created_by, " + q(TEACHER) + "), 'saarthi.' || a.kind, 1, (array['gemini','gemini','gemini','groq','ollama'])[1 + (abs(hashtext(a.id::text)) % 5)],")
    w("  (array['gemini-2.0-flash','gemini-2.0-flash','gemini-2.0-flash','llama-3.1-8b-instant','llama3.1:8b'])[1 + (abs(hashtext(a.id::text)) % 5)], encode(sha256(a.id::text::bytea), 'hex'),")
    w("  case when a.kind = 'parent_message' then 2 + abs(hashtext(a.id::text)) % 4 else 0 end, 900 + abs(hashtext(a.id::text)) % 1200, 300 + abs(hashtext(a.id::text)) % 900, 1400 + abs(hashtext(a.id::text)) % 6000,")
    w("  case when abs(hashtext(a.id::text)) % 17 = 0 then 'retried_valid' else 'valid' end, 'artifact', a.id, now() - (abs(hashtext(a.id::text)) % 85) * interval '1 day'")
    w("from artifacts a where a.school_id = " + q(SCHOOL) + " and a.origin = 'ai_generated';")
    w("insert into generation_log (school_id, actor_id, template_key, template_version, provider, model, redacted_prompt_hash, redaction_count, input_tokens, output_tokens, latency_ms, validation_result, artifact_type, artifact_id, created_at)")
    w("select i.school_id, coalesce(i.created_by, " + q(TEACHER) + "), 'prashna.items', 1, (array['gemini','gemini','groq'])[1 + (abs(hashtext(i.id::text)) % 3)], (array['gemini-2.0-flash','gemini-2.0-flash','llama-3.1-8b-instant'])[1 + (abs(hashtext(i.id::text)) % 3)],")
    w("  encode(sha256(i.id::text::bytea), 'hex'), 0, 700 + abs(hashtext(i.id::text)) % 800, 250 + abs(hashtext(i.id::text)) % 400, 1200 + abs(hashtext(i.id::text)) % 4000, 'valid', 'item', i.id, now() - (abs(hashtext(i.id::text)) % 85) * interval '1 day'")
    w("from items i where i.school_id = " + q(SCHOOL) + " and i.origin = 'ai_generated' and abs(hashtext(i.id::text)) % 3 = 0;")
    w("insert into generation_log (school_id, actor_id, template_key, template_version, provider, model, redacted_prompt_hash, redaction_count, input_tokens, output_tokens, latency_ms, validation_result, artifact_type, artifact_id, created_at)")
    w("select d.school_id, coalesce(d.drafted_by, " + q(TEACHER) + "), 'darpan.descriptor', 1, 'gemini', 'gemini-2.0-flash', encode(sha256(d.id::text::bytea), 'hex'), 3 + abs(hashtext(d.id::text)) % 5,")
    w("  1100 + abs(hashtext(d.id::text)) % 600, 180 + abs(hashtext(d.id::text)) % 200, 1600 + abs(hashtext(d.id::text)) % 3000, 'valid', 'descriptor', d.id, now() - (abs(hashtext(d.id::text)) % 40) * interval '1 day'")
    w("from hpc_descriptors d where d.school_id = " + q(SCHOOL) + ";")
    w("")
    w("-- snapshot the whole demo tenant for reset-demo (< 45 s)")
    w("select snapshot_demo(" + q(SCHOOL) + ");")
    (ROOT / "supabase/seed/0013_demo.sql").write_text("\n".join(L) + "\n")
    print(f"sections+{len(plan)} teachers=180 artifacts=180 timetable={len(rows)}")


if __name__ == "__main__":
    main()
