"""
Synthetic UDAY seed: a full scheme of work for Classes 3-8 (50 h/yr for 3-5,
100 h/yr for 6-8) across the five strands, plugged AND unplugged activity
variants for every unit, a Class 6 section ledger at exactly 64 delivered hours,
18 assessed projects, and CPD records. Writes supabase/seed/0012_uday.sql.
"""

import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCHOOL = "a0000000-0000-0000-0000-000000000001"
TEACHER = "d0000000-0000-0000-0000-000000000001"
ACADEMIC = "d0000000-0000-0000-0000-000000000002"
HOD = "d0000000-0000-0000-0000-000000000003"
SECTION_6A = "c0000000-0000-0000-0000-000000000001"
YEAR = "2026-27"


def uid(*parts):
    return str(uuid.uuid5(uuid.NAMESPACE_URL, "acharya/uday/" + "/".join(parts)))


def q(s):
    return "null" if s is None else "'" + str(s).replace("'", "''") + "'"


STRANDS = ["computational_thinking", "data_literacy", "ai_concepts", "ethics_and_bias", "applied_project"]
STRAND_TITLES = {
    "computational_thinking": ["Patterns and sequences", "Decomposing problems", "Algorithms in everyday life", "Debugging like a detective", "Abstraction: what matters"],
    "data_literacy": ["Collecting and sorting data", "Tables and pictographs", "Asking questions of data", "Bias in a sample", "Reading a chart honestly"],
    "ai_concepts": ["What can a computer learn?", "Teaching a machine with examples", "Recognising patterns in images", "How chatbots guess the next word", "Limits of AI"],
    "ethics_and_bias": ["Fair or unfair?", "Who is missing from the data?", "Privacy: what is mine to share", "When AI gets it wrong", "Rules for using AI at school"],
    "applied_project": ["Design a sorting game", "Build a class survey", "Train a picture sorter", "A fairness poster", "Showcase: our AI-safe project"],
}
GRADE_HOURS = {"3": 50, "4": 50, "5": 50, "6": 100, "7": 100, "8": 100}
# strand weights sum to 1
WEIGHTS = {"computational_thinking": 0.28, "data_literacy": 0.20, "ai_concepts": 0.20, "ethics_and_bias": 0.14, "applied_project": 0.18}


def main():
    L = []
    w = L.append
    w("-- 0012_uday.sql -- GENERATED by worker/scripts/gen_uday_seed.py. Do not hand-edit.")
    w("-- Scheme of work for Classes 3-8 (50 h / 100 h), plugged + unplugged activities per unit,")
    w("-- Class 6A ledger at 64 of 100 hours, 18 assessed projects, CPD records.")
    w("")
    w("insert into ct_ai_units (id, school_id, grade, sequence_no, title, big_idea, planned_hours, strand) values")
    units = []
    rows = []
    for grade, total in GRADE_HOURS.items():
        seq = 0
        for strand in STRANDS:
            n_units = 2 if grade in ("3", "4", "5") else 3
            hours_each = round(total * WEIGHTS[strand] / n_units, 1)
            for k in range(n_units):
                seq += 1
                title = STRAND_TITLES[strand][(int(grade) + k) % 5]
                uid_ = uid("unit", grade, str(seq))
                units.append((uid_, grade, seq, title, strand, hours_each))
                rows.append(f"  ({q(uid_)}, {q(SCHOOL)}, {q(grade)}, {seq}, {q(title + (' (' + ['I', 'II', 'III'][k] + ')' if n_units > 1 else ''))}, {q('Big idea: ' + title.lower() + ' — Grade ' + grade)}, {hours_each}, {q(strand)})")
    w(",\n".join(rows) + ";")
    # fix rounding so each grade sums exactly to 50 / 100: adjust the last applied_project unit
    w("")
    w("with sums as (select grade, sum(planned_hours) s from ct_ai_units where school_id = " + q(SCHOOL) + " group by grade)")
    w("update ct_ai_units u set planned_hours = u.planned_hours + (uday_required_hours(u.grade) - s.s) from sums s")
    w("where u.grade = s.grade and u.school_id = " + q(SCHOOL) + " and u.sequence_no = (select max(sequence_no) from ct_ai_units x where x.grade = u.grade and x.school_id = u.school_id);")
    w("")
    w("insert into ct_ai_activities (id, school_id, unit_id, title, mode, duration_minutes, materials, instructions_md, assessment_note) values")
    rows = []
    for uid_, grade, seq, title, strand, hours in units:
        rows.append(f"  ({q(uid('act', uid_, 'unplugged'))}, {q(SCHOOL)}, {q(uid_)}, {q(title + ' — unplugged')}, 'unplugged', 40, 'Paper, pencils, index cards', "
                    f"{q('1. Introduce the idea with a story from daily life.\\n2. Pairs act out the ' + strand.replace('_', ' ') + ' idea with cards.\\n3. Whole-class share; teacher records one observation per pair.')}, "
                    f"{q('Look for: correct sequence/reasoning explained aloud; no device needed.')})")
        rows.append(f"  ({q(uid('act', uid_, 'plugged'))}, {q(SCHOOL)}, {q(uid_)}, {q(title + ' — plugged')}, 'plugged', 40, 'Shared lab or one device per group', "
                    f"{q('1. Recap the unplugged version.\\n2. Groups repeat the task in a block-based tool or spreadsheet.\\n3. Save a screenshot as evidence.')}, "
                    f"{q('Look for: transfer from the unplugged version; evidence saved.')})")
        if strand == "applied_project":
            rows.append(f"  ({q(uid('act', uid_, 'hybrid'))}, {q(SCHOOL)}, {q(uid_)}, {q(title + ' — project session')}, 'hybrid', 80, 'Poster paper or a device', "
                        f"{q('Students plan, build and present a small project; rubric shared in advance.')}, {q('Assess with the project rubric; teacher enters scores and a comment.')})")
    w(",\n".join(rows) + ";")
    w("")
    # ledger: 6A at exactly 64 hours = 3840 minutes across sessions of 40 min (96 sessions), spread Apr-Sep
    w("insert into ct_ai_hours_ledger (school_id, section_id, academic_year, activity_id, delivered_on, minutes, teacher_id, note)")
    g6_units = [u for u in units if u[1] == "6"]
    rows = []
    for i in range(96):
        u = g6_units[i % len(g6_units)]
        mode = "unplugged" if i % 3 else "plugged"
        day = f"date '2026-04-06' + {i * 2}"   # every other day from April
        rows.append(f"  ({q(SCHOOL)}, {q(SECTION_6A)}, {q(YEAR)}, {q(uid('act', u[0], mode))}, {day}, 40, {q(TEACHER)}, {q('Session ' + str(i + 1))})")
    w("values\n" + ",\n".join(rows) + ";")
    w("")
    # 18 assessed projects for 6A students
    w("insert into ct_ai_projects (school_id, student_id, unit_id, title, rubric_scores, teacher_comment, assessed_by, assessed_on, submitted_at)")
    proj_unit = next(u for u in g6_units if u[4] == "applied_project")[0]
    w("select st.school_id, st.id, " + q(proj_unit) + ", 'Our class survey: what we eat at lunch', "
      "jsonb_build_object('problem_definition', 3, 'data_handling', 2 + (row_number() over ()) % 2, 'explanation', 3, 'ethics_reflection', 2), "
      "'Clear question, honest chart; next time note who was not asked.', " + q(TEACHER) + ", current_date - 10, now() - interval '12 days' "
      "from students st where st.section_id = " + q(SECTION_6A) + " order by st.admission_no limit 18;")
    w("")
    w("insert into cpd_records (school_id, teacher_id, activity, hours, completed_on) values")
    w(",\n".join([
        f"  ({q(SCHOOL)}, {q(TEACHER)}, 'District Level Deliberation', 6, date '2026-06-14')",
        f"  ({q(SCHOOL)}, {q(TEACHER)}, 'in-house', 2, date '2026-07-20')",
        f"  ({q(SCHOOL)}, {q(HOD)}, 'CBSE CoE workshop', 4, date '2026-05-30')",
        f"  ({q(SCHOOL)}, {q(ACADEMIC)}, 'District Level Deliberation', 3, date '2026-06-14')",
    ]) + ";")
    (ROOT / "supabase/seed/0012_uday.sql").write_text("\n".join(L) + "\n")
    print(f"units={len(units)} activities≈{len(units) * 2 + 18} ledger_sessions=96 (64 h)")


if __name__ == "__main__":
    main()
